### ISSUE TITLE
string-join vs mapconcat #'identity

### ISSUE THREAD

**Issue by progfolio** [vifon/tmsu.el#1]
Just an FYI that string-join is a defsubst for mapconcat #'identity as used here:

https://github.com/vifon/tmsu.el/blob/9f1e605c884a75eb4121afb10a097835bcdd7760/tmsu.el#L200-L211

**Comment by vifon** [comment]
Right, thanks for noticing! Since I already use `string-join` elsewhere, no reason to not use it here too. This will simplify this part a little.
