### ISSUE TITLE
How to not add --path to the tmsu command?

### ISSUE THREAD

**Issue by safijari** [vifon/tmsu.el#2]
My intent is to use this to navigate to files marked with a tag starting from anywhere. The seemingly mandatory inclusion of --path gets in the way of that. Any way to turn that off? For now I just edited the source code for my local package to remove that option.

**Comment by vifon** [comment]
Hello. I've just pushed a possible solution to the `query-in-subtree` branch. Can you check if this is the behavior you expect? Specifically I wonder if the `default-directory` should be switched to the root of the TMSU db or not. Currently the matching files higher than the current directory start with `../`, which works but might be unsightly.
